title: OU Thai Student Association
google_analytics: G-WQ161LH8W7
google_ads: AW-390929899
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
collections:
  exec_boards:
    output: true
  events:
    output: true
future: true